CatalogoLivros.Web/Models/Obra/AtivacaoDesativacao/ModelViewAtivacaoDesativacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using CatalogoLivros.Domain.Enum;

namespace CatalogoLivros.Web.Models.Obra.AtivacaoDesativacao
{
    public class ModelViewAtivacaoDesativacao
    {
        #region Dados da Obra

        [Display(Name = "Titulo:")]
        public string Titulo { get; set; }

        //________________________________________

        [Display(Name = "Gênero:")]
        public Genero Genero { get; set; }

        //________________________________________

        [Display(Name = "ISBN:")]
        public long ISBN { get; set; }

        //________________________________________

        [Display(Name = "Sinopse:")]
        public string Sinopse { get; set; }

        //________________________________________

        [Display(Name = "Status: ")]
        public StatusObra StatusObra { get; set; }

        #endregion


        #region Dados da Foto da Obra

        [Display(Name = "Selecione a Foto: ")]
        public HttpPostedFileBase FotoObra { get; set; }

        //________________________________________

        [Display(Name = "Descrição da Foto: ")]
        public string DescricaoFotoObra { get; set; }

        //________________________________________

        public string CaminhoFotoObra { get; set; }

        #endregion


        #region Dados do Autor da Obra

        [Display(Name = "Nome do Autor:")]
        public string NomeAutor { get; set; }

        //________________________________________

        [Display(Name = "Descrição do Autor:")]
        public string DescricaoAutor { get; set; }

        #endregion


        #region Dados da Editora da Obra

        [Display(Name = "Nome da Editora:")]
        public string NomeEditora { get; set; }

        //________________________________________

        [Display(Name = "Descrição da Editora:")]
        public string DescricaoEditora { get; set; }

        //________________________________________

        [Display(Name = "Tipo da Editora:")]
        public TipoEditora TipoEditora { get; set; }

        #endregion
    }
}

CatalogoLivros.Web/Models/Obra/Atualizacao/ModelViewAtualizacaoObra.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using CatalogoLivros.Domain.Enum;

namespace CatalogoLivros.Web.Models.Obra.Atualizacao
{
    public class ModelViewAtualizacaoObra
    {
        #region Dados da Obra

        [Display(Name = "Titulo:")]
        public string Titulo { get; set; }

        //________________________________________

        [Display(Name = "Gênero:")]
        public Genero Genero { get; set; }

        //________________________________________

        [Display(Name = "ISBN:")]
        public long ISBN { get; set; }

        //________________________________________

        [Display(Name = "Sinopse:")]
        public string Sinopse { get; set; }

        #endregion


        #region Dados da Foto da Obra

        [Display(Name = "Selecione a Foto: ")]
        public HttpPostedFileBase FotoObra { get; set; }

        //________________________________________

        [Display(Name = "Descrição da Foto: ")]
        public string DescricaoFotoObra { get; set; }

        //________________________________________

        public string CaminhoFotoObra { get; set; }

        #endregion


        #region Dados do Autor da Obra

        [Display(Name = "Nome do Autor:")]
        public string NomeAutor { get; set; }

        //________________________________________

        [Display(Name = "Descrição do Autor:")]
        public string DescricaoAutor { get; set; }

        #endregion


        #region Dados da Editora da Obra

        [Display(Name = "Nome da Editora:")]
        public string NomeEditora { get; set; }

        //________________________________________

        [Display(Name = "Descrição da Editora:")]
        public string DescricaoEditora { get; set; }

        //________________________________________

        [Display(Name = "Tipo da Editora:")]
        public TipoEditora TipoEditora { get; set; }

        #endregion
    }
}

CatalogoLivros.Web/Models/Obra/Exibicao/ModelViewExibicaoObras.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using CatalogoLivros.Domain.Enum;

namespace CatalogoLivros.Web.Models.Obra.Exibicao
{
    public class ModelViewExibicaoObras
    {
        #region Dados da Obra

        [Display(Name = "Titulo:")]
        public string Titulo { get; set; }

        //________________________________________

        [Display(Name = "Gênero:")]
        public Genero Genero { get; set; }

        //________________________________________

        [Display(Name = "ISBN:")]
        public long ISBN { get; set; }

        //________________________________________

        [Display(Name = "Sinopse:")]
        public string Sinopse { get; set; }

        //________________________________________

        [Display(Name = "Status: ")]
        public StatusObra StatusObra { get; set; }

        #endregion


        #region Dados da Foto da Obra

        [Display(Name = "Selecione a Foto: ")]
        public HttpPostedFileBase FotoObra { get; set; }

        //________________________________________

        [Display(Name = "Descrição da Foto: ")]
        public string DescricaoFotoObra { get; set; }

        //________________________________________

        public string CaminhoFotoObra { get; set; }

        #endregion


        #region Dados do Autor da Obra

        [Display(Name = "Nome do Autor:")]
        public string NomeAutor { get; set; }

        //________________________________________

        [Display(Name = "Descrição do Autor:")]
        public string DescricaoAutor { get; set; }

        #endregion


        #region Dados da Editora da Obra

        [Display(Name = "Nome da Editora:")]
        public string NomeEditora { get; set; }

        //________________________________________

        [Display(Name = "Descrição da Editora:")]
        public string DescricaoEditora { get; set; }

        //________________________________________

        [Display(Name = "Tipo da Editora:")]
        public TipoEditora TipoEditora { get; set; }

        #endregion
    }
}

CatalogoLivros.Web/Controllers/ObraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CatalogoLivros.Domain.Entity;
using CatalogoLivros.Web.Models.Obra.Cadastro;
using CatalogoLivros.Web.Models.Obra.Atualizacao;
using CatalogoLivros.Web.Models.Obra.Exibicao;
using CatalogoLivros.Web.Models.Obra.Pesquisa;
using CatalogoLivros.Web.Models.Obra.AtivacaoDesativacao;
using CatalogoLivros.DAL.Persistence.PersistenceObra;
using CatalogoLivros.Domain.Enum;
using CatalogoLivros.SGBDDAL.DataSource;
using PagedList;

namespace CatalogoLivros.Web.Controllers
{
    [Authorize]
    public class ObraController : Controller
    {
        ModelViewAtivacaoDesativacao modelDadosObra = new ModelViewAtivacaoDesativacao();

        #region Páginas

        public ActionResult Index()
        {
            return View();
        }

        //____________________________________________

        public ActionResult CadastroObra()
        {
            return View();
        }

        //____________________________________________

        public ActionResult AtualizacaoObra()
        {
            return View();
        }

        //____________________________________________

        public ActionResult AtivacaoDesativacaoObra()
        {
            return View();
        }

        //____________________________________________

        public ActionResult PesquisaObra()
        {
            return View();
        }

        //____________________________________________

        public ActionResult ExibicaoObras()
        {
            return this.ExibirObras(null);
        }

        //____________________________________________

        public ActionResult ExibicaoObrasAtivas()
        {
            return this.ExibirObrasAtivas(null);
        }

        //____________________________________________

        public ActionResult ExibicaoObrasInativas()
        {
            return this.ExibirObrasInativas(null);
        }

        //____________________________________________

        public ActionResult CatalogoServicosFuncionalidades()
        {
            return View();
        }

        #endregion


        #region Métodos

        [HttpPost]
        public ActionResult CadastrarObra(ModelViewCadastroObra modelObra)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    Obra obra = new Obra();
                    obra.AutorObra = new Autor();
                    FotoObra fotoObra = new FotoObra();
                    obra.EditoraObra = new Editora();
                    ObraDal obraDal = new ObraDal();

                    obra.Titulo = modelObra.Titulo;
                    obra.Genero = modelObra.Genero;

                    modelObra.ISBN = modelObra.ISBN;
                    obra.ISBN = obraDal.ReturnConvertionISBNByLong(modelObra.ISBN);
                    obra.Sinopse = modelObra.Sinopse;
                    obra.StatusObra = modelObra.StatusObra;

                    fotoObra.Foto = modelObra.FotoObra.FileName;
                    fotoObra.Descricao = modelObra.DescricaoFotoObra;

                    obra.AutorObra.Nome = modelObra.NomeAutor;
                    obra.AutorObra.Descricao = modelObra.DescricaoAutor;

                    obra.EditoraObra.Nome = modelObra.NomeEditora;
                    obra.EditoraObra.TipoEditora = modelObra.TipoEditora;
                    obra.EditoraObra.Descricao = modelObra.DescricaoEditora;

                    Obra obraExists = obraDal.FindObraByTituloISBN(obra.Titulo, obra.ISBN);

                    if(obraExists != null)
                    {
                        ViewBag.MensagemErro = "Esta Obra já está cadastrada. Tente novamente.";
                    }
                    else
                    {
                        string tipoExtensaoFoto = modelObra.FotoObra.ContentType;
                        string foto = modelObra.FotoObra.FileName;

                        tipoExtensaoFoto = obraDal.ReturnExtensionFoto(tipoExtensaoFoto, foto);

                        fotoObra.Foto = Guid.NewGuid().ToString() + "." + tipoExtensaoFoto;
                        fotoObra.Descricao = modelObra.DescricaoFotoObra;

                        Usuario usuarioAutenticado = (Usuario)Session["usuarioAutenticado"];
                        if(usuarioAutenticado != null)
                        {
                            string pathFotoObra = HttpContext.Server.MapPath("/Fotos/FotoObra/") + usuarioAutenticado.Nome.ToLower() + "_" + usuarioAutenticado.Login.ToLower() + "\\" + obra.ISBN + "_" + obra.Titulo.ToLower();
                            obraDal.CreateDirectoryFoto(pathFotoObra);
                            pathFotoObra = obraDal.ReturnFotoFull(pathFotoObra, fotoObra.Foto);
                            modelObra.FotoObra.SaveAs(pathFotoObra); // usa a classe da Model de Cliente e não a classe da Entidade de Cliente.
                            fotoObra.CaminhoFotoObra = pathFotoObra;
                            obraDal.Insert(obra, fotoObra);
                            ModelState.Clear();
                            ViewBag.MensagemOK = "A Obra " + obra.Titulo + " foi cadastrada com sucesso.";
                        }
                        else
                        {
                            Response.Redirect("/Home/Index");
                        }
                    }
                }
                return View("CadastroObra");
            }
            catch(NotImplementedException ex)
            {
                throw new NotImplementedException("Ocorreu o seguinte erro: " + ex.Message);
            }
            catch (Exception ex)
            {
                throw new Exception("Ocorreu o seguinte erro: " + ex.Message);
            }
        }

        //_______________________________________________________________________

        [HttpPost]
        public ActionResult AtualizarObra(ModelViewAtualizacaoObra modelAtualizacaoObra)
        {

            return null;
        }

        //_______________________________________________________________________

        [HttpGet]
        public ActionResult PesquisarObra(ModelViewPesquisaObra modelViewPesquisaObra)
        {
            try
            {
                ModelViewPesquisaObra modelDadosObra = new ModelViewPesquisaObra();
                bool flagViewBag = false;
                if (string.IsNullOrEmpty(modelViewPesquisaObra.Titulo) && string.IsNullOrEmpty(modelViewPesquisaObra.NomeAutor) && modelViewPesquisaObra.ISBN == 0)
                {
                    ViewBag.MensagemErro = "Erro. Preencha pelo menos um campo.";
                    flagViewBag = true;
                }
                else
                {
                    using (DBCatalogoLivros dbCatalogoLivros = new DBCatalogoLivros())
                    {
                        Obra obra = new Obra();
                        obra.AutorObra = new Autor();
                        obra.EditoraObra = new Editora();
                        FotoObra fotoObra = new FotoObra();
                        ObraDal obraDal = new ObraDal();

                        string[] collectionParam = new string[4];
                        collectionParam = obraDal.ReturnParam(modelViewPesquisaObra.Titulo, modelViewPesquisaObra.NomeAutor, modelViewPesquisaObra.ISBN);
                        if (Convert.ToInt32(collectionParam[3]) == 0)
                        {
                            ViewBag.MensagemErro = "Erro. Preencha pelo menos um campo.";
                        }
                        else
                        {
                            if (Convert.ToInt32(collectionParam[3]) == 3)
                            {
                                obra = obraDal.FindObra(modelViewPesquisaObra.Titulo, modelViewPesquisaObra.NomeAutor, modelViewPesquisaObra.ISBN);
                            }
                            if (Convert.ToInt32(collectionParam[3]) == 2)
                            {
                                obra = obraDal.ReturnTypeParam(collectionParam);
                            }
                            if (Convert.ToInt32(collectionParam[3]) == 1)
                            {
                                obra = obraDal.ReturnTypeParam(collectionParam);
                            }
                        }
                        if (obra == null)
                        {
                            ViewBag.MensagemErro = "Não foi encontrada nenhuma Obra pesquisada.";
                            return View("PesquisaObra");
                        }
                        obra.AutorObra = obraDal.ReturnDataAutor(obra);
                        obra.EditoraObra = obraDal.ReturnDataEditora(obra);
                        fotoObra = obraDal.ReturnFotoObra(obra);

                        ModelViewPesquisaObra itensObra = new ModelViewPesquisaObra();

                        string[] foto = fotoObra.CaminhoFotoObra.Split('\\');

                        Usuario usuarioAutenticado = (Usuario)Session["usuarioAutenticado"];
                        if(usuarioAutenticado != null)
                        {
                            itensObra.CaminhoFotoObra = "/Fotos/FotoObra/" + usuarioAutenticado.Nome.ToLower() + "_" + usuarioAutenticado.Login.ToLower() + "/" + obra.ISBN + "_" + obra.Titulo.ToLower() + "/" + foto[12];
                            itensObra.Titulo = obra.Titulo;
                            itensObra.Genero = obra.Genero;
                            itensObra.ISBN = obra.ISBN;
                            itensObra.StatusObra = obra.StatusObra;
                            itensObra.Sinopse = obra.Sinopse;

                            itensObra.NomeAutor = obra.AutorObra.Nome;
                            itensObra.DescricaoAutor = obra.AutorObra.Descricao;

                            itensObra.NomeEditora = obra.EditoraObra.Nome;

CatalogoLivros.Web/Views/Obra/AtivacaoDesativacaoObra.cshtml
@model CatalogoLivros.Web.Models.Obra.AtivacaoDesativacao.ModelViewAtivacaoDesativacao
@{
    ViewBag.Title = "Ativacao e Desativacao de Obras";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Obra - Ativação e Desativação de <br />Obras</h2>
<a href="/Obra/CatalogoServicosFuncionalidades">Voltar</a>
@using (Html.BeginForm("PesquisarObrasAtivasDesativas", "Obra", FormMethod.Get))
{
    @Html.AntiForgeryToken()
    <hr />
    <aside class="textoSucesso">
        <p>
            @ViewBag.MensagemOk
        </p>
    </aside>
    <aside class="textoErro">
        <p>
            @ViewBag.MensagemErro
        </p>
    </aside>
    if (string.IsNullOrEmpty(ViewBag.MensagemErro))
    {
        <aside class="textoErro">
            <p>
                @Html.ValidationSummary()
            </p>
        </aside>   
    }
    <fieldset>
        <table>
            <tr>
                <th class="tdPesquisa">
                    @Html.LabelFor(model => model.Titulo)
                </th>
                <th class="tdPesquisa">
                    @Html.TextBoxFor(model => model.Titulo, new { @autofocus = true, @class = "elementosFormulario", @placeholder = "Título da Obra..." })
                </th>
            </tr>
            <tr>
                <th class="tdPesquisa">
                    @Html.LabelFor(model => model.NomeAutor)
                </th>
                <th class="tdPesquisa">
                    @Html.TextBoxFor(model => model.NomeAutor, new { @class = "elementosFormulario", @placeholder = "Nome do Autor..." })
                </th>
            </tr>
            <tr>
                <th class="tdPesquisa">
                    @Html.LabelFor(model => model.ISBN)
                </th>
                <th class="tdPesquisa">
                    @Html.TextBoxFor(model => model.ISBN, new { @class = "elementosFormulario", @placeholder = "ISBN da Obra..." })
                </th>
            </tr>
            <tr>
                <th class="tdPesquisa">
                    <input type="submit" value="Pesquisar Obra" class="btn btn-primary" />
                </th>
            </tr>
        </table>
    </fieldset>
}

@{
    if (Model != null)
    {
        using (Html.BeginForm("AtivarDesativarObras", "Obra", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <br />
            <fieldset>
                <table border="0" cellpadding="0" cellspacing="0" class="table">
                    <tr>
                        <th colspan="5">
                            <h3 class="h3">Dados da Obra</h3>
                        </th>
                    </tr>
                    <tr>
                        <th class="td">
                            <img class="imgObras" src="@Model.CaminhoFotoObra" alt="@Model.Titulo" title="@Model.Titulo" width="100" height="120" />
                        </th>
                        <th class="td">
                            @Html.DisplayNameFor(model => model.Titulo)<br />
                            @Html.DisplayFor(modelItem => Model.Titulo)
                        </th>
                        <th class="td">
                            @Html.DisplayNameFor(model => model.Genero)<br />
                            @Html.DisplayFor(modelItem => Model.Genero)
                        </th>
                        <th class="td">
                            @Html.DisplayNameFor(model => model.ISBN)<br />
                            @Html.DisplayFor(modelItem => Model.ISBN)
                            @Html.HiddenFor(modelItem => Model.ISBN)
                        </th>
                        <th class="td">
                            @Html.DisplayNameFor(model => model.StatusObra)
                        </th>
                        <th class="td">
                            @Html.EnumDropDownListFor(model => model.StatusObra, new { @class = "elementosFormulario" })
                        </th>
                    </tr>
                    <tr>
                        <th class="td" colspan="5">
                            @Html.DisplayNameFor(model => model.Sinopse)<br />
                            @Html.DisplayFor(modelItem => Model.Sinopse)
                        </th>
                    </tr>
                </table>

                <table border="0" cellpadding="0" cellspacing="0" class="table">
                    <tr>
                        <th colspan="2">
                            <h3 class="h3">Dados do Autor</h3>
                        </th>
                    </tr>
                    <tr>
                        <th class="td">
                            @Html.DisplayNameFor(model => model.NomeAutor)<br />
                            @Html.DisplayFor(modelItem => Model.NomeAutor)
                        </th>
                        <th class="td">
                            @Html.DisplayNameFor(model => model.DescricaoAutor)<br />
                            @Html.DisplayFor(modelItem => Model.DescricaoAutor)
                        </th>
                    </tr>
                </table>

                <table border="0" cellpadding="0" cellspacing="0" class="table">
                    <tr>
                        <th colspan="2">
                            <h3 class="h3">Dados da Editora</h3>
                        </th>
                    </tr>
                    <tr>
                        <th class="td">
                            @Html.DisplayNameFor(model => model.NomeEditora)<br />
                            @Html.DisplayFor(modelItem => Model.NomeEditora)
                        </th>
                        <th class="td">
                            @Html.DisplayNameFor(model => model.TipoEditora)<br />
                            @Html.DisplayFor(modelItem => Model.TipoEditora)
                        </th>
                    </tr>
                    <tr>
                        <th class="tdPesquisa">
                            <br />
                            <input type="submit" value="Ativar/Desativar Obra" class="btn btn-success" />
                        </th>
                    </tr>
                </table>
            </fieldset>
        }
    }
}

CatalogoLivros.Web/Views/Obra/AtualizacaoObra.cshtml
@model CatalogoLivros.Web.Models.Obra.Atualizacao.ModelViewAtualizacaoObra
@{
    ViewBag.Title = "Obras - Atualizacar Obra";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Obras - Atualizar Obra</h2>
<a href="/Obra/CatalogoServicosFuncionalidades">Voltar</a>
@{
    using (Html.BeginForm("PesquisarAtualizarObras", "Obra", FormMethod.Get))
    {
        @Html.AntiForgeryToken()
        <hr />
        <aside class="textoErro">
            <p>
                @ViewBag.MensagemErro
            </p>
        </aside>
        if (string.IsNullOrEmpty(ViewBag.MensagemErro))
        {
            <aside class="textoErro">
                <p>
                    @Html.ValidationSummary()
                </p>
            </aside>
        }
        <fieldset>
            <table border="0" cellpadding="0" cellspacing="0">
                <tr>
                    <td class="tdPesquisa">
                        @Html.LabelFor(model => model.Titulo)
                    </td>
                    <td class="tdPesquisa">
                        @Html.TextBoxFor(model => model.Titulo, new { @autofocus = true, @class = "elementosFormulario", @placeholder = "Título da Obra..." })
                    </td>
                </tr>
                <tr>
                    <td class="tdPesquisa">
                        @Html.LabelFor(model => model.NomeAutor)
                    </td>
                    <td class="tdPesquisa">
                        @Html.TextBoxFor(model => model.NomeAutor, new { @class = "elementosFormulario", @placeholder = "Nome do Autor..." })
                    </td>
                </tr>
                <tr>
                    <td class="tdPesquisa">
                        @Html.LabelFor(model => model.ISBN)
                    </td>
                    <td class="tdPesquisa">
                        @Html.TextBoxFor(model => model.ISBN, new { @class = "elementosFormulario", @placeholder = "ISBN da Obra..." })
                    </td>
                </tr>
                <tr>
                    <td class="tdPesquisa">
                        <input type="submit" value="Pesquisar Obra" class="btn btn-primary" />
                    </td>
                </tr>
            </table>
        </fieldset>
    }
}

@{
    if(Model != null)
    {
        using (Html.BeginForm("AtualizarObra", "Obra", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <aside class="textoSucesso">
                <p>
                    @ViewBag.MensagemOk
                </p>
            </aside>
            <aside class="textoErro">
                <p>
                    @ViewBag.MensagemErro
                </p>
            </aside>
            <aside class="textoErro">
                <p>
                    @Html.ValidationSummary()
                </p>
            </aside>
            <fieldset>
                <br /><h3 class="h3">Dados da Obra</h3>
                <table border="0" cellpadding="0" cellspacing="0">
                    <tr>
                        <th class="td">
                            @Html.LabelFor(itemModel => Model.Titulo)
                        </th>
                        <th class="td">
                            @Html.TextBoxFor(itemModel => Model.Titulo, new { @class = "elementosFormulario", @placeholder = "Título da Obra do Usuário..." })
                        </th>
                        <th class="td">
                            @Html.LabelFor(itemModel => itemModel.Genero)
                        </th>
                        <th class="td">
                            @Html.EnumDropDownListFor(itemModel => itemModel.Genero, "Selecione o Gênero", new { @class = "elementosFormulario" })
                        </th>
                    </tr>
                    <tr>
                        <th class="td" valign="top">
                            @Html.LabelFor(itemModel => Model.ISBN)
                        </th>
                        <th class="td" valign="top">
                            @Html.TextBoxFor(itemModel => Model.ISBN, new { @id = "txtISBN", @maxlength = "13", @class = "elementosFormulario", @placeholder = "ISBN da Obra do Usuário..." })
                        </th>
                        <th class="td" valign="top">
                            @Html.LabelFor(itemModel => itemModel.Sinopse)
                        </th>
                        <th class="td">
                            @Html.TextAreaFor(itemModel => itemModel.Sinopse, new { @class = "elementosFormulario", @cols = "21", @rows = "6", @placeholder = "Sinópse da Obra do Usuário..." })
                        </th>
                    </tr>
                </table>
                <h3 class="h3">Dados do Autor</h3>
                <table border="0" cellpadding="0" cellspacing="0">
                    <tr>
                        <th class="td" valign="top">
                            @Html.LabelFor(itemModel => Model.NomeAutor)
                        </th>
                        <th class="td" valign="top">
                            @Html.TextBoxFor(itemModel => Model.NomeAutor, new { @class = "elementosFormulario", @placeholder = "Nome do Autor da Obra do Usuário..." })
                        </th>
                        <th class="td" valign="top">
                            @Html.LabelFor(itemModel => itemModel.DescricaoAutor)
                        </th>
                        <th class="td">
                            @Html.TextAreaFor(itemModel => itemModel.DescricaoAutor, new { @class = "elementosFormulario", @cols = "21", @rows = "6", @placeholder = "Descrição do Autor da Obra do Usuário..." })
                        </th>
                    </tr>
                </table>
                <h3 class="h3">Dados da Editora</h3>
                <table border="0" cellpadding="0" cellspacing="0">
                    <tr>
                        <th class="td">
                            @Html.LabelFor(itemModel => itemModel.NomeEditora)
                        </th>
                        <th class="td">
                            @Html.TextBoxFor(itemModel => itemModel.NomeEditora, new { @class = "elementosFormulario", @placeholder = "Nome da Editora da Obra do Usuário..." })
                        </th>
                        <th class="td">
                            @Html.LabelFor(itemModel => itemModel.TipoEditora)
                        </th>
                        <th class="td">
                            @Html.EnumDropDownListFor(itemModel => itemModel.TipoEditora, "Selecione o Tipo da Editora", new { @class = "elementosFormulario" })
                        </th>
                    </tr>
                    <tr>
                        <th class="td" valign="top">
                            @Html.LabelFor(itemModel => itemModel.DescricaoEditora)
                        </th>
                        <th class="td">
                            @Html.TextAreaFor(itemModel => itemModel.DescricaoEditora, new { @class = "elementosFormulario", @cols = "21", @rows = "6", @placeholder = "Descrição da Editora da Obra do Usuário..." })
                        </th>
                    </tr>
                    <tr>
                        <th class="td">
                            <input type="submit" value="Atualizar Obra" class="btn btn-success" />
                        </th>
                    </tr>
                </table>
            </fieldset>
        }
    }
}

CatalogoLivros.Web/Views/Obra/Index.cshtml
@{
    ViewBag.Title = "Obras - Catálogo de Livros Online";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Obras - Catálogo de Livros Online</h2>
<hr />
<p class="paragrafo">
    Seja Bem-Vindo a seção de Obras.
</p>
<br />
<p class="paragrafo">
    A seção de Obras foi criada especialmente para você que já possue um cadastro no sistema 
    <span class="bold">Catálogo de Livros Online</span>. Essa seção é disponibilizada apenas para 
    pessoas cadastradas no sistema. Isto quer dizer que você já deu um grande passo em já estar
    aqui, pois todo o processo de criação de seu cadastro foi concluído com êxito.
</p>
<p class="paragrafo">
    O <span class="bold">Catálogo de Livros Online</span> quer parabeniza-lo por você ter se 
    associado ao Sistema Online.
</p>
<p class="paragrafo">
    Clique <a href="/Obra/CatalogoServicosFuncionalidades">aqui</a> para ser redirecionado para página de <span class="italic">Catálogo
    de Funcionalidades e Serviços</span> e poder usurfluir do seu mais novo sistema de catálogo de obras online feito
    especialmente para você.
</p>